CREATE TABLE `clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320),
	`phone` varchar(20),
	`company` varchar(255),
	`position` varchar(100),
	`address` text,
	`postalCode` varchar(10),
	`city` varchar(100),
	`country` varchar(100) DEFAULT 'France',
	`category` enum('prospect','active','vip','inactive') NOT NULL DEFAULT 'prospect',
	`status` enum('active','inactive') NOT NULL DEFAULT 'active',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `company` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`legalName` varchar(255),
	`siret` varchar(14),
	`tvaNumber` varchar(20),
	`address` text,
	`postalCode` varchar(10),
	`city` varchar(100),
	`country` varchar(100) DEFAULT 'France',
	`phone` varchar(20),
	`email` varchar(320),
	`website` varchar(255),
	`logoUrl` text,
	`bankName` varchar(255),
	`iban` varchar(34),
	`bic` varchar(11),
	`defaultTvaRate` decimal(5,2) DEFAULT '20.00',
	`defaultPaymentTerms` int DEFAULT 30,
	`legalMentions` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `company_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documentLines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`documentId` int NOT NULL,
	`description` text NOT NULL,
	`quantity` decimal(10,2) DEFAULT '1.00',
	`unit` varchar(50) DEFAULT 'unité',
	`unitPriceHt` decimal(10,2) NOT NULL,
	`tvaRate` decimal(5,2) NOT NULL,
	`totalHt` decimal(10,2) NOT NULL,
	`totalTva` decimal(10,2) NOT NULL,
	`totalTtc` decimal(10,2) NOT NULL,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `documentLines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`projectId` int,
	`type` enum('quote','invoice','credit_note') NOT NULL,
	`number` varchar(50) NOT NULL,
	`status` enum('draft','sent','accepted','rejected','paid','cancelled') NOT NULL DEFAULT 'draft',
	`date` timestamp NOT NULL,
	`dueDate` timestamp,
	`validityDate` timestamp,
	`subject` varchar(255),
	`introduction` text,
	`conclusion` text,
	`notes` text,
	`totalHt` decimal(10,2) NOT NULL,
	`totalTva` decimal(10,2) NOT NULL,
	`totalTtc` decimal(10,2) NOT NULL,
	`discountAmount` decimal(10,2) DEFAULT '0.00',
	`paymentTerms` int DEFAULT 30,
	`paymentMethod` enum('bank_transfer','check','card','cash','other'),
	`isAcompteRequired` boolean DEFAULT false,
	`acomptePercentage` decimal(5,2),
	`acompteAmount` decimal(10,2),
	`pdfUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `documents_id` PRIMARY KEY(`id`),
	CONSTRAINT `documents_number_unique` UNIQUE(`number`)
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`type` enum('website','app','coaching','ia_integration','optimization','other') NOT NULL,
	`status` enum('draft','active','on_hold','completed','cancelled') NOT NULL DEFAULT 'draft',
	`priority` enum('low','normal','high','urgent') DEFAULT 'normal',
	`startDate` timestamp,
	`endDate` timestamp,
	`estimatedHours` decimal(10,2),
	`budgetEstimate` decimal(10,2),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int,
	`clientId` int,
	`title` varchar(255) NOT NULL,
	`description` text,
	`status` enum('todo','in_progress','review','done','cancelled') NOT NULL DEFAULT 'todo',
	`priority` enum('low','normal','high','urgent') DEFAULT 'normal',
	`dueDate` timestamp,
	`completedAt` timestamp,
	`estimatedHours` decimal(10,2),
	`isBillable` boolean DEFAULT true,
	`hourlyRate` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `timeEntries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taskId` int,
	`projectId` int,
	`clientId` int,
	`description` text,
	`startTime` timestamp NOT NULL,
	`endTime` timestamp,
	`duration` int,
	`isBillable` boolean DEFAULT true,
	`hourlyRate` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `timeEntries_id` PRIMARY KEY(`id`)
);
